-- insert some books
insert into `book`
    (`title`, `difficulty`, `description`)
values
    ('Beginning Programming with Java For Dummies', 'EASY', 'Do you wish to speak Java like a professional? Well, in case you wish to speak the Java lingo like a pro while being a dummy, in the beginning, this book is the best as it provides you with a no-nonsense guide that shows you how to create a program in Java, how to put various pieces together, how to handle the standard programming challenges in Java and so on. Beginning Programming with Java For Dummies will help you to ‘speak’ Java as it starts with basic concepts like variables, methods, loops and arrays, objects, classes, etc. Also, this book is updated with Java 9 so you can learn the language with various samples.'),
    ('Effective Java', 'INTERMEDIATE', 'If you have understood Java fundamentals and now want to get some real work done, then Effective Java is one of the finest & the best Java books for experts! It will help you get an in-depth education about the seventy-eight programmer’s rules of thumb, which are working solutions for the various commonly available programming challenges. The topics included in Effective Java include the new design patterns that demonstrate the best of various features ranging from generics to enums, annotations to autoboxing. All of these concepts are explained clearly and concisely using many examples to make sure you get them right.'),
    ('Head First Java: A Brain-Friendly Guide', 'EASY', 'In case you are bored of slogging through Java how-to manuals, then Head-First Java is the way to go! This book is a brain-friendly guide (As its name suggests!) and it provides a more visual format to engage your brain rather than a text-heavy approach that can become boring pretty fast. Head-First Java starts the Java journey from basic programming fundamentals and moves on to advanced topics and is often considered one of the best books for Java programming for beginners which include threads, network sockets, distributed programming with RMI, etc. So Head-First Java is basically a multi-sensory learning experience that will help you in becoming a bonafide Java programmer in no time!'),
    ('Java: The Complete Reference', 'ADVANCE', 'If you are at the intermediate or expert level in Java and want a “back to the basics” approach, then this book is the way to go as it’s a well-structured and complete source on Java programming with examples from the real world for all topics. Java: The Complete Reference covers the whole of Java, including fundamental topics like syntax, keywords, and basic programming principles. And also the complex topics like the Java API library, the concurrency utilities, Swing, JavaBeans, servlets, etc. An introduction to JShell is also provided, which is Java’s interactive programming tool.'),
    ('Thinking in Java', 'INTERMEDIATE', 'If you want to think in Java my friends, Thinking in Java is the book for you!!! It is a hands-on guide that will thoroughly instruct you in writing the most efficient Java code by using the best features of Java. This book contains 500+ working Java programs in 700+ compiling files, that are rewritten for the newest edition of Java in this book. Thinking in Java begins with an object-oriented introduction for both beginners and experts and then follows it with topics like Design patterns, Introduction to XML, Concurrency, etc. All in all, this is a book that will remain a relevant source of knowledge for you even after years of studying and coding in Java.'),
    ('Core Java Volume I – Fundamentals', 'INTERMEDIATE', 'If you want to understand the core of Java fundamentals, then Core Java Volume I is the book for you! It will help you get an in-depth education about Java and API with the help of lots of examples, most of which reflect modularization that demonstrates code that is easier to manage and evolve. Core Java Volume I – Fundamentals has chapters with topics ranging from the basics like variables, data structures, objects, and classes to the advances like objects, generics, collections, lambda expressions, Swing design, concurrency, and functional programming.');
